# Generated by Django 6.0.7 on 2026-07-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_runs', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='ASSIGNED', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery_runs.deliveryrun')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stop', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery Stop',
                'verbose_name_plural': 'Delivery Stops',
                'ordering': ['stop_sequence'],
                'indexes': [models.Index(fields=['delivery_run'], name='delivery_st_deliver_4bcd42_idx'), models.Index(fields=['order'], name='delivery_st_order_i_10b010_idx'), models.Index(fields=['status'], name='delivery_st_status_94b895_idx'), models.Index(fields=['stop_sequence'], name='delivery_st_stop_se_1160b2_idx')],
            },
        ),
    ]
