# Generated by Django 6.0.7 on 2026-07-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('COMPLETED', 'Completed'), ('CASH_BANKED', 'Cash Banked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_banked_at', models.DateTimeField(blank=True, null=True)),
                ('cash_banked_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_runs', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Delivery Run',
                'verbose_name_plural': 'Delivery Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='delivery_ru_status_66e009_idx'), models.Index(fields=['driver'], name='delivery_ru_driver__ba469f_idx'), models.Index(fields=['created_at'], name='delivery_ru_created_d94484_idx'), models.Index(fields=['started_at'], name='delivery_ru_started_883315_idx')],
            },
        ),
    ]
